---

- hosts: all
  remote_user: vagrant
  sudo: yes

  tasks:

    - name: update apt
      action: command /usr/bin/apt-get update

    - name: add nginx ppa
      action: apt_repository repo=ppa:nginx/stable state=present

    - name: install nginx package
      action: apt pkg=nginx state=installed
